url: http://seanmaass.net
name: Sean Maass' Blog
title: Sean Maass' Blog
description: Sean Maass' Blog
author: Sean Maass

permalink: /blog/:year/:month/:day/:title/
timezone: "America/Phoenix"

# RSS / Email (optional) subscription links (change if using something like Feedburner)
subscribe_rss: /atom.xml
subscribe_email:
# RSS feeds can list your email address if you like
email: sean@seanmaass.net

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #
highlighter: rouge

exclude:     ["Gemfile*", "Rakefile", "*.sublime-project", "*.sublime-workspace"]

paginate: 10          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section

excerpt_separator: "\n\n\n"
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

category_dir: categories

titlecase: true       # Converts page and post titles to titlecase

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "post"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "page"
    values:
      layout: "page"

sitemap:
  exclude:
    - "/atom.xml"
    - "/feed.xml"
    - "/feed/index.xml"
    - "403.html"
    - "404.html"
    - "405.html"
    - "5xx.html"
    - "maintenance.html"

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in /source/_includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: []

# Each layout uses the default asides, but they can have their own asides instead. Simply uncomment the lines below
# and add an array with the asides you want to use.
# blog_index_asides:
# post_asides:
# page_asides:

# ----------------------- #
#    Octoflat Theme       #
# ----------------------- #
navigation:
- text: Home
  url: /
- text: Archives
  url: /archives

# ----------------------- #
# Jekyll Asset Pipeline   #
# ----------------------- #
assets:
  js_compressor:  uglifier
  css_compressor: sass
  sources:
    - _assets/fonts
    - _assets/javascripts
    - _assets/styleimages
    - _assets/stylesheets

# ----------------------- #
#   Jekyll Image Tag    #
# ----------------------- #
image:
  source: _assets/images
  output: assets/images
  presets:
    default: # Full width pictures
      attr:
        class: "img-responsive center-block"
      width: 350
    half: # Half width pictures
      attr:
        class: "img-responsive center-block"
      width: 200


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: seanmaass
github_repo_count: 3
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_user: seanmaass
twitter_tweet_button: true

# Google +1
google_plus_one: true
google_plus_one_size: medium

# Google Plus Profile
# Hidden: No visible button, just add author information to search results
googleplus_user: +SeanMaass
googleplus_hidden: false

# LinkedIn Profile
linkedin_user: seanmaass

# Pinboard
pinboard_user:
pinboard_count: 3

# Delicious
delicious_user:
delicious_count: 3

# AddThis Sharing Profile
addthis_profile_id:

# Disqus Comments
disqus_short_name: seanmaassnet
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-50182282-1
google_analytics_domain_name: seanmaass.net

# Facebook Like
facebook_like: true
